# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4a0bc6ba1e24bd265718385ed2d3089d0f3640b59b65d171c69848062e61e1b806bf8e3c7bceb942a090653d13f94a843a500aaa35f60284dbbccdbef96e300

test:
  secret_key_base: f8584075314165bc1f70232acf272c6be9f2d4fa339634d3942e921e51533f4e932c15cc25152433f0bc7774c7738ee08b7e4d543fd903663392613d0154de2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
